#!/usr/bin/env python3
from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RULES_DIR = ROOT / ".ai" / "rules"
CURSOR_RULES_DIR = ROOT / ".cursor" / "rules"
GENERATED_CURSOR_PREFIX = ""
GENERATED_MARKER = "<!-- generated-by: sync-agent-rules.py -->"


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8").strip() + "\n"


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug or "rule"


def parse_order_and_name(path: Path) -> tuple[int, str]:
    stem = path.stem
    match = re.match(r"^(\d+)[-_](.+)$", stem)
    if match:
        return int(match.group(1)), match.group(2)
    return 9999, stem


def list_rule_files() -> list[Path]:
    files = [path for path in RULES_DIR.glob("*.md") if path.is_file()]
    return sorted(
        files,
        key=lambda path: (
            parse_order_and_name(path)[0],
            parse_order_and_name(path)[1].lower(),
            path.name.lower(),
        ),
    )


def extract_title(body: str, fallback: str) -> str:
    for line in body.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return fallback


def extract_applies_to(body: str) -> str | None:
    match = re.search(r"^Applies to:\s*(.+)$", body, re.MULTILINE)
    if not match:
        return None
    return match.group(1).strip()


def parse_scope_for_cursor(applies_to: str | None) -> tuple[bool, str | None]:
    if not applies_to:
        return False, None

    lowered = applies_to.lower()
    if "all" in lowered:
        return True, None

    if "`" in applies_to:
        globs = ",".join(part.strip() for part in re.findall(r"`([^`]+)`", applies_to) if part.strip())
        if globs:
            return False, globs

    return False, applies_to


def tool_doc(tool_name: str, body: str) -> str:
    return (
        f"# {tool_name} Instructions\n\n"
        "This file is generated by `scripts/sync-agent-rules.py`.\n"
        "Do not edit this file directly. Edit files in `.ai/rules/` and re-run sync.\n\n"
        f"{body}"
    )


def write(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)}")


def build_cursor_rule(description: str, globs: str | None, always_apply: bool, body: str) -> str:
    frontmatter = [
        "---",
        f"description: {description}",
    ]
    if globs:
        frontmatter.append(f"globs: {globs}")
    frontmatter.append(f"alwaysApply: {'true' if always_apply else 'false'}")
    frontmatter.append("---")
    return "\n".join(frontmatter) + f"\n\n{GENERATED_MARKER}\n\n" + body


def cleanup_old_cursor_rules() -> None:
    CURSOR_RULES_DIR.mkdir(parents=True, exist_ok=True)
    for path in CURSOR_RULES_DIR.glob(f"{GENERATED_CURSOR_PREFIX}*.mdc"):
        path.unlink()
        print(f"removed {path.relative_to(ROOT)}")


def main() -> None:
    rule_files = list_rule_files()
    if not rule_files:
        raise SystemExit("No rule files found in .ai/rules/")

    rules: list[tuple[Path, str]] = [(path, read_text(path)) for path in rule_files]
    combined_body = "\n---\n\n".join(body for _, body in rules)

    combined = (
        combined_body
        + "\n\n"
        + "## Sync process\n\n"
        + "- Canonical sources live under `.ai/rules/`.\n"
        + "- Every `.md` file in `.ai/rules/` is included automatically.\n"
        + "- Run `python3 scripts/sync-agent-rules.py` after updates.\n"
        + "- Commit canonical rule files and this sync script; generated outputs stay ignored from Git and Docker context.\n"
    )

    write(ROOT / "AGENTS.md", tool_doc("AGENTS", combined))
    write(ROOT / "CLAUDE.md", tool_doc("Claude", combined))
    write(ROOT / "CLINE.md", tool_doc("Cline", combined))
    write(ROOT / "CODEX.md", tool_doc("Codex", combined))

    cleanup_old_cursor_rules()

    for index, (path, body) in enumerate(rules):
        order, clean_name = parse_order_and_name(path)
        title = extract_title(body, fallback=path.stem)
        applies_to = extract_applies_to(body)
        always_apply, globs = parse_scope_for_cursor(applies_to)
        cursor_body = build_cursor_rule(
            description=title,
            globs=globs,
            always_apply=always_apply,
            body=body,
        )
        output_index = order if order != 9999 else index
        filename = f"{GENERATED_CURSOR_PREFIX}{output_index:02d}-{slugify(clean_name)}.mdc"
        write(CURSOR_RULES_DIR / filename, cursor_body)


if __name__ == "__main__":
    main()
